name: ds-snus

services:

  postgres:
    image: postgres:18

    environment:
      POSTGRES_DB: SNUS
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gorki123


  ingestion:
    build:
      context: .
      dockerfile: IngestionService/Dockerfile


  consensus:
    build:
      context: .
      dockerfile: ConsensusService/Dockerfile


  notification:
    build:
      context: .
      dockerfile: NotificationService/Dockerfile


  ingress:
    build:
      context: .
      dockerfile: Ingress/Dockerfile